
'use server';
/**
 * @fileOverview Extracts entities and a corresponding JSON Schema from a collection of documents using AI.
 *
 * - extractEntitiesFromDocuments - A function that handles the entity extraction process.
 * - ExtractEntitiesFromDocumentsInput - The input type for the function.
 * - ExtractEntitiesFromDocumentsOutput - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ExtractEntitiesFromDocumentsInputSchema = z.object({
  documents: z.array(
    z.object({
      url: z.string().describe('The data URI of the document.'),
    })
  ),
});

export type ExtractEntitiesFromDocumentsInput = z.infer<
  typeof ExtractEntitiesFromDocumentsInputSchema
>;

const ExtractEntitiesFromDocumentsOutputSchema = z.object({
  extractedJson: z.object({
    entities: z.any().describe('An object where keys are the extracted entity names and values are the extracted entity values.'),
    schema: z.any().describe('A valid JSON schema object describing the extracted entities. Each property in the schema should have a \"description\" explaining what the entity represents.'),
  }).describe('The structured JSON containing both the extracted key-value pairs and their corresponding JSON schema with descriptions.')
});

export type ExtractEntitiesFromDocumentsOutput = z.infer<
  typeof ExtractEntitiesFromDocumentsOutputSchema
>;

import { withCache } from '@/lib/cache';

export async function extractEntitiesFromDocuments(
  input: ExtractEntitiesFromDocumentsInput
): Promise<ExtractEntitiesFromDocumentsOutput> {
  return withCache('extractEntities', input, () => extractEntitiesFlow(input));
}

const extractEntitiesPrompt = ai.definePrompt({
  name: 'extractEntitiesPrompt',
  input: { schema: ExtractEntitiesFromDocumentsInputSchema },
  output: {
    format: 'json',
    schema: ExtractEntitiesFromDocumentsOutputSchema,
  },
  prompt: `### PERSONA
Você é um Especialista em Processamento de Linguagem Natural e Automação de Documentos Jurídicos. Sua tarefa é extrair dados de documentos de texto e mapeá-los para variáveis específicas de um modelo de contrato.

### PROCESSO DE PENSAMENTO (Mental Cleanup)
Antes de extrair qualquer dado, siga estas etapas:
1. **Identificação de Ruído:** Identifique tags de formatação HTML (ex: <em>, <li>, <p>, <span>, <div>).
2. **Filtro de Fechamento:** Descarte imediatamente qualquer termo que comece com "/" (ex: </li>, </em>, /EM, /LI), pois são apenas fechamentos de estilo ou ruídos de formatação.
3. **Isolamento de Variáveis:** Foque apenas no que está entre \`< >\` e descreve dados de negócio (ex: <título do projeto>, <nome do coordenador>, <objeto>).
4. **Extração Pura:** Ignore as tags de estilo ao redor dos dados e extraia apenas a informação semântica contida nos documentos.

### OBJETIVO
Identificar e extrair todas as informações que correspondem a potenciais variáveis de um modelo (geralmente indicadas por termos descritivos como "Nome", "Data", "Valor", etc., ou encontradas entre \`< >\` no contexto do usúario).

### DOCUMENTOS PARA ANÁLISE
{{#each documents}}
- {{media url=this.url}}
{{/each}}

### DIRETRIZES DE EXTRAÇÃO
1. **Identificação de Variáveis:** O modelo utiliza o padrão \`<nome da variável>\` para indicar onde os dados devem ser inseridos. Tente antecipar essas variáveis extraindo as informações chave do documento.
2. **Eliminação de Ruído (CRÍTICO):** Ignore COMPLETAMENTE qualquer tag que pareça formatação HTML.
   - NÃO extraia termos como: \`EM\`, \`LI\`, \`OL\`, \`P\`, \`STRONG\`, \`SPAN\`, \`DIV\`, \`BR\`.
   - NÃO extraia nada que comece com \`/\`.
3. **Extração Semântica:** Busque nos documentos fornecidos a informação que melhor se encaixe no contexto de um contrato administrativo.

### REGRAS DE FORMATAÇÃO
- **Chaves (Keys):** Use \`SNAKE_CASE_MAIÚSCULO\` (ex: \`VALOR_TOTAL_CONTRATO\`). Evite nomes de tags HTML.
- **Valores (Values):** Extraia o texto exatamente como aparece no documento. Se for data, mantenha o formato original.
- **Descrições (Schema):** Crie explicações técnicas para cada campo.

### FORMATO DE SAÍDA (JSON)
Retorne estritamente um JSON com a seguinte estrutura:
{
  "entities": { "CHAVE": "Valor" },
  "schema": {
    "type": "object",
    "properties": {
      "CHAVE": { "type": "string", "description": "Explicação concisa" }
    }
  }
}

### REGRAS CRÍTICAS
- Não invente informações. Se não houver dados, retorne objetos vazios.
- Nunca retorne tags HTML (como EM, LI, P) como chaves de entidades.
- Agrupe endereços em uma única string coerente se estiverem espalhados.
`,
});

const extractEntitiesFlow = ai.defineFlow(
  {
    name: 'extractEntitiesFlow',
    inputSchema: ExtractEntitiesFromDocumentsInputSchema,
    outputSchema: ExtractEntitiesFromDocumentsOutputSchema,
  },
  async input => {
    const llmResponse = await extractEntitiesPrompt(input);
    const output = llmResponse.output;

    if (!output) {
      throw new Error('No output was generated by the AI.');
    }

    return {
      extractedJson: output.extractedJson,
    };
  }
);
