
'use server';
/**
 * @fileOverview Extracts entities from a collection of documents using AI.
 *
 * - extractEntitiesFromDocuments - A function that handles the entity extraction process.
 * - ExtractEntitiesFromDocumentsInput - The input type for the function.
 * - ExtractEntitiesFromDocumentsOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtractEntitiesFromDocumentsInputSchema = z.object({
  documents: z.array(
    z.object({
      url: z.string().describe('The data URI of the document.'),
    })
  ),
});

export type ExtractEntitiesFromDocumentsInput = z.infer<
  typeof ExtractEntitiesFromDocumentsInputSchema
>;

const ExtractEntitiesFromDocumentsOutputSchema = z.object({
  extractedJson: z
    .any()
    .describe('The structured JSON with the keys and values found.'),
});

export type ExtractEntitiesFromDocumentsOutput = z.infer<
  typeof ExtractEntitiesFromDocumentsOutputSchema
>;

export async function extractEntitiesFromDocuments(
  input: ExtractEntitiesFromDocumentsInput
): Promise<ExtractEntitiesFromDocumentsOutput> {
  return extractEntitiesFlow(input);
}

const extractEntitiesPrompt = ai.definePrompt({
  name: 'extractEntitiesPrompt',
  input: {schema: ExtractEntitiesFromDocumentsInputSchema},
  output: {
    format: 'json',
    schema: ExtractEntitiesFromDocumentsOutputSchema,
  },
  prompt: `Instrução:
Analise os documentos fornecidos e identifique todas as informações variáveis — ou seja, elementos que mudariam entre versões diferentes do mesmo tipo de documento.

Os documentos para análise são:
{{#each documents}}
- {{media url=this.url}}
{{/each}}

As variáveis incluem:

Nomes de pessoas, cargos e instituições
Datas
Valores monetários
Números de processos, contratos ou documentos
Títulos e descrições específicas de projetos ou instrumentos
Termos ou expressões que representam detalhes únicos

Output esperado:
Um JSON estruturado com as chaves e valores encontrados, no seguinte formato:

{
  "NOME_DO_REITOR": "Alfredo Macedo Gomes",
  "NOME_DA_UNIVERSIDADE": "Universidade Federal de Pernambuco",
  "NOME_DA_ENTIDADE_PARCEIRA": "Coordenação de Aperfeiçoamento de Pessoal de Nível Superior",
  "NOME_DA_FUNDACAO_INTERVENIENTE": "FADE",
  "TIPO_DE_INSTRUMENTO_JURIDICO": "Instrumento Novo TED",
  "NOME_DO_PROJETO": "Automação na Gestão de Processos de Cobranças Administrativas da CAPES",
  "UNIDADE_RESPONSAVEL": "CIn/UFPE",
  "NUMERO_DO_TED": "13260/2023",
  "NUMERO_DO_PROCESSO": "23076.xxxxx/yyyy-yy",
  "NOME_FISCAL_TITULAR": "Fulano de Tal",
  "CPF_FISCAL_TITULAR": "000.000.000-00",
  "NOME_FISCAL_SUPLENTE": "Beltrano de Tal",
  "CPF_FISCAL_SUPLENTE": "111.111.111-11",
  "LOCAL_E_DATA": "Recife, 20 de outubro de 2023"
}

Regras de saída:

O resultado deve ser apenas o JSON, sem comentários ou explicações extras.
Se algum campo não existir no documento, simplesmente omita-o.
Use os nomes das chaves em MAIÚSCULAS e com underscores (_).
Converta valores numéricos e monetários para strings, mantendo o formato original.
`,
});

const extractEntitiesFlow = ai.defineFlow(
  {
    name: 'extractEntitiesFlow',
    inputSchema: ExtractEntitiesFromDocumentsInputSchema,
    outputSchema: ExtractEntitiesFromDocumentsOutputSchema,
  },
  async input => {
    const llmResponse = await extractEntitiesPrompt(input);
    const output = llmResponse.output;

    if (!output) {
      throw new Error('No output was generated by the AI.');
    }

    return {
      extractedJson: output.extractedJson,
    };
  }
);
