
'use server';
/**
 * @fileOverview Extracts entities and a corresponding JSON Schema from a collection of documents using AI.
 *
 * - extractEntitiesFromDocuments - A function that handles the entity extraction process.
 * - ExtractEntitiesFromDocumentsInput - The input type for the function.
 * - ExtractEntitiesFromDocumentsOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtractEntitiesFromDocumentsInputSchema = z.object({
  documents: z.array(
    z.object({
      url: z.string().describe('The data URI of the document.'),
    })
  ),
});

export type ExtractEntitiesFromDocumentsInput = z.infer<
  typeof ExtractEntitiesFromDocumentsInputSchema
>;

const ExtractEntitiesFromDocumentsOutputSchema = z.object({
  extractedJson: z.object({
    entities: z.record(z.any()).describe('An object where keys are the extracted entity names and values are the extracted entity values.'),
    schema: z.any().describe('A valid JSON schema object describing the extracted entities. Each property in the schema should have a "description" explaining what the entity represents.'),
  }).describe('The structured JSON containing both the extracted key-value pairs and their corresponding JSON schema with descriptions.')
});

export type ExtractEntitiesFromDocumentsOutput = z.infer<
  typeof ExtractEntitiesFromDocumentsOutputSchema
>;

export async function extractEntitiesFromDocuments(
  input: ExtractEntitiesFromDocumentsInput
): Promise<ExtractEntitiesFromDocumentsOutput> {
  return extractEntitiesFlow(input);
}

const extractEntitiesPrompt = ai.definePrompt({
  name: 'extractEntitiesPrompt',
  input: {schema: ExtractEntitiesFromDocumentsInputSchema},
  output: {
    format: 'json',
    schema: ExtractEntitiesFromDocumentsOutputSchema,
  },
  prompt: `Instrução:
Analise os documentos fornecidos e execute duas tarefas:
1.  Identifique todas as informações variáveis — ou seja, elementos que mudariam entre versões diferentes do mesmo tipo de documento (nomes, datas, valores, etc.).
2.  Para cada variável identificada, crie uma descrição concisa que explique o seu significado no contexto do documento.

Os documentos para análise são:
{{#each documents}}
- {{media url=this.url}}
{{/each}}

Output esperado:
Um único objeto JSON que contenha duas chaves principais: "entities" e "schema".

1.  "entities": Um objeto contendo os pares de chave-valor das informações extraídas.
    *   As chaves devem ser em MAIÚSCULAS e com underscores (ex: "NOME_DO_REITOR").
    *   Os valores devem ser strings, mantendo o formato original do documento.

2.  "schema": Um objeto JSON Schema que descreve a estrutura de "entities".
    *   Deve ter "type": "object".
    *   A chave "properties" deve conter um objeto onde cada chave corresponde a uma chave em "entities".
    *   Cada propriedade dentro de "properties" deve ser um objeto com "type": "string" e uma "description" que explica o que aquela variável representa.

Exemplo de Output:
{
  "entities": {
    "NOME_DO_REITOR": "Alfredo Macedo Gomes",
    "NOME_DA_UNIVERSIDADE": "Universidade Federal de Pernambuco",
    "NUMERO_DO_PROCESSO": "23076.xxxxx/yyyy-yy"
  },
  "schema": {
    "type": "object",
    "properties": {
      "NOME_DO_REITOR": {
        "type": "string",
        "description": "O nome completo do reitor da universidade."
      },
      "NOME_DA_UNIVERSIDADE": {
        "type": "string",
        "description": "O nome oficial da universidade mencionada no documento."
      },
      "NUMERO_DO_PROCESSO": {
        "type": "string",
        "description": "O número de identificação único do processo administrativo."
      }
    }
  }
}

Regras de saída:
- O resultado deve ser APENAS o JSON, sem comentários ou explicações extras.
- Se nenhum campo for encontrado, retorne um objeto com "entities" e "schema" vazios.
`,
});

const extractEntitiesFlow = ai.defineFlow(
  {
    name: 'extractEntitiesFlow',
    inputSchema: ExtractEntitiesFromDocumentsInputSchema,
    outputSchema: ExtractEntitiesFromDocumentsOutputSchema,
  },
  async input => {
    const llmResponse = await extractEntitiesPrompt(input);
    const output = llmResponse.output;

    if (!output) {
      throw new Error('No output was generated by the AI.');
    }

    return {
      extractedJson: output.extractedJson,
    };
  }
);
