
'use server';
/**
 * @fileOverview Provides detailed feedback on uploaded documents using a customizable system prompt.
 *
 * - getDocumentFeedback - A function that handles the feedback generation process.
 * - GetDocumentFeedbackInput - The input type for the getDocumentfeedback function.
 * - GetDocumentFeedbackOutput - The return type for the getDocumentFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { fileSearch, search } from '../services/file-search';

const GetDocumentFeedbackInputSchema = z.object({
  systemPrompt: z.string().describe('The customizable system prompt to guide the AI feedback.'),
  fileIds: z.array(z.string()).describe('An array of file IDs to be searched.'),
});

export type GetDocumentFeedbackInput = z.infer<typeof GetDocumentFeedbackInputSchema>;

const GetDocumentFeedbackOutputSchema = z.object({
  feedback: z.string().describe('The detailed feedback generated by the AI in Markdown format.'),
});

export type GetDocumentFeedbackOutput = z.infer<typeof GetDocumentFeedbackOutputSchema>;


export async function getDocumentFeedback(input: GetDocumentFeedbackInput): Promise<GetDocumentFeedbackOutput> {
  return getDocumentFeedbackFlow(input);
}

const getDocumentFeedbackPrompt = ai.definePrompt({
  name: 'getDocumentFeedbackPrompt',
  input: {schema: GetDocumentFeedbackInputSchema},
  output: {schema: GetDocumentFeedbackOutputSchema},
  tools: [fileSearch, search],
  prompt: `{{systemPrompt}}

Analise os documentos disponíveis através da ferramenta fileSearch e forneça um feedback detalhado com base no prompt do sistema.
`,
});


const getDocumentFeedbackFlow = ai.defineFlow(
  {
    name: 'getDocumentFeedbackFlow',
    inputSchema: GetDocumentFeedbackInputSchema,
    outputSchema: GetDocumentFeedbackOutputSchema,
  },
  async (input) => {
    const {output} = await getDocumentFeedbackPrompt(input);
    if (!output) {
      throw new Error("AI failed to generate feedback.");
    }
    return output;
  }
);
